### ISSUE TITLE
Help !!

### ISSUE THREAD

**Issue by abdelkrimkr** [alexmamo/CloudStorageJetpackCompose#1]
How I can Use This Code to select A more types of files 
In one lunch 
Like 
"aplication/pdf ",
"application/msword"
And others 
Help me 
With that Codes
```
val galleryLauncher =  rememberLauncherForActivityResult(GetContent()) { imageUri ->
        imageUri?.let {
            viewModel.addImageToStorage(imageUri)
        }
    }

```

`galleryLauncher.launch(ALL_IMAGES)`
And Thanks

**Comment by AlexMamo** [comment]
With that code, you can only select images from the gallery. If you want to select multiple types of files, you should first read them from the location they exist and then add them to the Storage.
